# rest端口号
server:
  port: 8000

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: Passw0rd!
    timeout: 5000

thread:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 5
    # 队列容量
    queue-capacity: 50
    # 线程名称前缀
    thread-name-prefix: lesser-pander-thread

# mybatis
mybatis:
  # mapper位置
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
    # 使全局的映射器启用或禁用缓存
    cache-enabled: true
    # 全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    lazy-loading-enabled: true
    # 当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载
    aggressive-lazy-loading: true
    # 是否允许单条sql返回多个数据集
    multiple-result-sets-enabled: true
    # 是否可以使用列的别名
    use-column-label: true
    # 允许JDBC生成主键,需要驱动器支持。如果设为了true，这个设置将强制使用被生成的主键，有一些驱动器不兼容不过仍然可以执行
    use-generated-keys: true
    # 指定MyBatis如何自动映射数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
    auto-mapping-behavior: partial
    # 这是默认的执行类型 (SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新)
    default-executor-type: simple
    # 使用驼峰命名法转换字段
    map-underscore-to-camel-case: true
    # 设置本地缓存范围 session:就会有数据的共享 statement:语句范围 (这样就不会有数据的共享)
    local-cache-scope: session
    # 设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型
    jdbc-type-for-null: null
    # 返回字段为空时也返回对应的key
    call-setters-on-nulls: true
    # sql打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

# 邮箱验证码有效时间/秒
code:
  expiration: 300

# 密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==

# sm.ms 图床的 token
smms:
  token: 1oOP3ykFDI0K6ifmtvU7c8Y1eTWZSlyl
